name: The Bible Shop
favicon: null
layout_spectrum: 0.9143932978622615
typography_spectrum: 0.5558988880366087
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.08672765176743269
  lightness: 0.7109561963006854
  saturation: 0.26394418929703534
  rhythmicContrast: 0.014409034745767713
purpose: []
